CREATE TABLE Students(
	StudentID INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Exams(
	ExamID INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE StudentsExams(
	StudentID INT NOT NULL REFERENCES Students(StudentID),
	ExamID INT NOT NULL REFERENCES Exams(ExamID),
	PRIMARY KEY(StudentID, ExamID)
)
