CREATE TABLE Passports(
	PassportID INT PRIMARY KEY IDENTITY,
	PassportNumber CHAR(8) NOT NULL
)

CREATE TABLE Persons (
	PersonID INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	Salary DECIMAL(7,2) NOT NULL,
	PassportID INT NOT NULL FOREIGN KEY REFERENCES Passports(PassportID) UNIQUE
)